import { StyleSheet } from 'react-native';

export const colors = {
  background: '#FFFDD0',
  white: '#FFFFFF',
  text: '#836F68',
  textSecondary: '#836F68',
  heading: '#836F68',
  muted: '#836F68',
  border: '#E8E2D5',
  placeholder: '#C4B8A9',
  primary: '#FFAA56',
  student: '#FFAA56',
  professor: '#88C688',
  tutor: '#94C0DF',
  purple: '#9E82C0',
  success: '#88C688',
  danger: '#E53935',
  dangerBackground: '#FFEBEE',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  dashboardContainer: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 20,
    justifyContent: 'space-between',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 28,
  },
  // NOVO ESTILO ADICIONADO AQUI PARA A IMAGEM
  logoImage: {
    width: 400,
    height: 120,
    resizeMode: 'contain',
  },
  logoContainerWelcome: {
    alignItems: 'center',
    marginBottom: 32,
  },
  logoBadgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  logoSubtitle: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.muted,
    letterSpacing: 0.5,
    marginTop: 2,
  },
  card: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: colors.white,
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 28,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: colors.heading,
    textAlign: 'center',
    marginBottom: 24,
  },
  signUpCardTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.heading,
    textAlign: 'center',
    marginBottom: 24,
  },
  inputGroup: { marginBottom: 16 },
  label: {
    fontSize: 14,
    color: colors.textSecondary,
    marginBottom: 6,
    fontWeight: '500',
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.white,
  },
  button: {
    backgroundColor: colors.primary,
    height: 48,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
  },
  buttonPressed: { opacity: 0.9 },
  buttonText: { color: colors.white, fontSize: 16, fontWeight: '600' },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  cardFooterText: { fontSize: 14, color: colors.muted },
  signUpLink: { fontSize: 14, fontWeight: '600', textDecorationLine: 'underline', color: colors.success },

  buttonRow: { flexDirection: 'row', gap: 12, marginTop: 8 },
  backButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: colors.muted,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  backButtonText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '600',
  },
  submitButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submitButtonText: { color: colors.white, fontSize: 15, fontWeight: '600' },

  title: {
    fontSize: 22,
    fontWeight: '600',
    color: colors.heading,
    textAlign: 'center',
    marginBottom: 28,
  },
  cardsContainer: { width: '100%', maxWidth: 380, gap: 16 },
  welcomeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  cardPressed: { opacity: 0.9, transform: [{ scale: 0.99 }] },
  iconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  cardTextContainer: { flex: 1, justifyContent: 'center' },
  welcomeCardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 2,
  },
  cardSubtitle: { fontSize: 13, color: '#A39585' },
  footer: { marginTop: 36 },
  loginLink: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.success,
    textDecorationLine: 'underline',
  },

  header: { alignItems: 'center', marginTop: 20 },
  avatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.text,
  },
  roleBadgeStudent: {
    fontSize: 14,
    color: colors.student,
    fontWeight: '600',
    marginTop: 4,
  },
  roleBadgeProfessor: {
    fontSize: 14,
    color: colors.professor,
    fontWeight: '600',
    marginTop: 4,
  },
  roleBadgeTutor: {
    fontSize: 14,
    color: colors.tutor,
    fontWeight: '600',
    marginTop: 4,
  },
  content: { flex: 1, marginTop: 40 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.heading,
    marginBottom: 12,
  },
  dashboardCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: 16,
    elevation: 2,
  },
  dashboardCardText: { fontSize: 14, color: colors.textSecondary },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 14,
    backgroundColor: colors.dangerBackground,
    borderRadius: 14,
  },
  logoutText: {
    color: colors.danger,
    fontWeight: '600',
    fontSize: 15,
  },

  registerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  registerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: colors.text,
  },
  registerSpacer: { height: 15 },

  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});