import { StyleSheet } from "react-native";
const Estilos = StyleSheet.create({
  container: { flex: 1 },
  tela: { gap: 20, padding: 15 },
  titulo: {
    marginTop: 50,
    marginBottom: 30,
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
  },
  cardPerfil: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    flexDirection: "column",
    elevation: 5,
  },
  cardTutorial: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  cardConfig: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    gap: 10,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  cardTema: {
    backgroundColor: "#FFFDD0",
    borderRadius: 15,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  cardOpcoes: {
    backgroundColor: "#FFFDD0",
    borderRadius: 15,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  cardNotiChat: {
    backgroundColor: "#FFFDD0",
    borderRadius: 15,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  cardLembrete: {
    backgroundColor: "#FFFDD0",
    borderRadius: 15,
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  botaoSair: {
    backgroundColor: "#fe0505",
    borderRadius: 15,
    padding: 20,
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
  },
  textoBotaoSair: { color: "#fff", fontSize: 18 },
  texto: { fontSize: 18 },
  texto2: { fontSize: 18 },
  textoConfiguracoes: {},
  navbar: { marginBottom: 50, alignItems: "center" },
  perfilTopo: { flexDirection: "row", alignItems: "center" },
  avatarContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#94C0DF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 18,
  },
  avatarTexto: { fontSize: 42 },
  informacoesPerfil: { flex: 1, gap: 4 },
  nomePerfil: { fontWeight: "bold" },
  tipoPerfil: { fontWeight: "600" },
  detalhesPerfil: { marginTop: 2 },
  botaoAvatar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    marginTop: 18,
  },
  textoBotaoAvatar: { fontWeight: "600" },
  botoesTema: { flexDirection: "row", gap: 8, width: "100%" },
  botaoTema: {
    flex: 1,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },

    cabecalhoConfig: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    marginTop: 0,
  },

  botaoAlerta: {
    backgroundColor: "#FF8C42",
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 10,
    elevation: 3,
  },

  textoAlerta: {
    color: "#fff",
    fontWeight: "bold",
  },
});
export default Estilos;