import { StyleSheet } from "react-native";

const Estilos = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFDD0" },
  header: { width: "100%", paddingHorizontal: 15, marginTop: 12 },
  topRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 12,
    gap: 8,
  },
  headerTitle: {
    flex: 1,
    flexShrink: 1,
    fontSize: 30,
    fontWeight: "bold",
    minWidth: 0,
  },
  taskCount: { fontSize: 14, color: "#666", marginBottom: 10 },
  inputContainer: {
    flexDirection: "row",
    padding: 16,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginRight: 12,
    fontSize: 16,
  },
  addButton: {
    backgroundColor: "#94C0DF",
    borderRadius: 8,
    minWidth: 38,
    minHeight: 38,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 5,
    paddingVertical: 5,
    flexShrink: 0,
    elevation: 3,
  },
  taskList: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    paddingBottom: 0,
    paddingTop: 0,
  },
  cardEvento: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 2,
    padding: 15,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  checkbox: { marginRight: 4 },
  taskText: { flex: 1, fontSize: 16, color: "#333" },
  completedTaskText: { textDecorationLine: "line-through", color: "#999" },
  deleteButton: { padding: 8 },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#999",
    marginTop: 16,
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: "#999",
    marginTop: 8,
    textAlign: "center",
  },
  /*Parte feita com IA até o BotaoConfirmar*/ modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  scrollModal: { flexGrow: 1, justifyContent: "center", alignItems: "center" },
  cardModal: {
    width: "92%",
    maxWidth: 520,
    maxHeight: "85%",
    borderRadius: 15,
    overflow: "hidden",
  },
  tituloModal: { fontSize: 20, fontWeight: "bold", marginBottom: 20 },
  opcaoContainer: {
    flexDirection: "row",
    alignItems: "center",
    maxWidth: "100%",
    marginRight: 20,
  },
  opcoesRow: {
    flexDirection: "row",
    marginBottom: 15,
    flexWrap: "wrap",
    gap: 12,
  },
  radioExterno: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#4B6CB7",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    flexShrink: 0,
  },
  radioInterno: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#4B6CB7",
  },
  textoOpcao: {
    fontSize: 16,
    flexShrink: 1,
  },
  botoesModal: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    alignItems: "stretch",
    marginTop: 20,
    gap: 12,
  },
  botaoCancelar: {
    backgroundColor: "#FFAA56",
    borderRadius: 10,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 14,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  botaoConfirmar: {
    backgroundColor: "#94C0DF",
    borderRadius: 10,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 14,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  textoBotao: {
    fontSize: 16,
    textAlign: "center",
    flexShrink: 1,
    maxWidth: "100%",
  },
  infoTarefa: { gap: 10 },
  textosInfo: {
    borderWidth: 1,
    borderColor: "#dbdbdb",
    borderRadius: 10,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  titulosInfoTarefa: { marginTop: 20 },
  buttons: { marginBottom: 50, alignItems: "center" },
  topoCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  tituloEvento: {
    fontSize: 18,
    fontWeight: "bold",
    flexGrow: 1,
    flexShrink: 1,
    minWidth: "55%",
  },

  badgeTipo: {
    backgroundColor: "#94C0DF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 15,
    alignSelf: "flex-start",
  },

  textoTipo: { color: "#fff", fontWeight: "bold" },
  textoTipoAdicionar: { paddingBottom: 15 },
  textodataEvento: {},

  botaoAlerta: {
    backgroundColor: "#FF8C42",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    elevation: 3,
  },

  textoAlerta: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },

  tituloSecao: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
    marginLeft: 5,
  },
  modalContent: {},

  campoData: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
  },

  seletorData: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#dbdbdb",
    borderRadius: 12,
    padding: 4,
    overflow: "hidden",
  },

  botaoFecharCalendario: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },

  fecharReforco: {
    minWidth: 44,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  overlayReforco: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 24,
  },

  modalReforco: {
    width: "100%",
    maxWidth: 420,
    maxHeight: "85%",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#88C688",
    overflow: "hidden",
  },

  conteudoReforco: {
    padding: 24,
    alignItems: "center",
    gap: 16,
  },

  tituloReforco: {
    fontWeight: "bold",
    textAlign: "center",
  },

  textoReforco: {
    textAlign: "center",
    width: "100%",
  },

  botaoContinuarReforco: {
    width: "100%",
    backgroundColor: "#88C688",
    minHeight: 48,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 8,
    alignItems: "center",
    justifyContent: "center",
  },

  textoBotaoReforco: {
    fontWeight: "bold",
    textAlign: "center",
  },

  rodapeCriador: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    marginTop: 12,
    width: "100%",
  },

  textoCriador: {
    flexShrink: 1,
    textAlign: "right",
  },
});
export default Estilos;